name: Build My Supermarket APK 🛒
on:
  push:
    branches:
      - main
  workflow_dispatch: # عشان تشغله يدوي في أي وقت

jobs:
  buildForAndroid:
    name: Build for Android 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Cache Library ⚡
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-Android
          restore-keys: |
            Library-

      - name: Build Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
          androidAppBundle: false # عشان يطلع APK مش AAB
          unityVersion: 2022.3.0f1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Supermarket-Build
          path: build/Android
          
