name: Build My Supermarket APK 🛒

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildForAndroid:
    name: Build for Android 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
          unityVersion: 2022.3.0f1
          androidAppBundle: false

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Supermarket-Build
          path: build/Android
